name: release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release"
        required: false
        default: nightly

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt install -y libgtk-4-dev

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: tar.zst
        run: |
          # hardcodes relative path for NVIM_GTK_RUNTIME_PATH in binary
          DESTDIR=dist/release/nvim-gtk-linux-x86_64/_/
          make DESTDIR=$DESTDIR PREFIX=.. install
          rmdir $DESTDIR

          tar caf dist/release/nvim-gtk-linux-x86_64.tar.zst -C dist/release/ nvim-gtk-linux-x86_64

      - uses: actions/upload-artifact@v5
        with:
          name: nvim-gtk-linux-x86_64
          path: |
            dist/release/nvim-gtk-linux-x86_64.tar.zst
          retention-days: 1

  publish:
    needs: [linux]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/download-artifact@v6

      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
      - if: env.TAG_NAME == 'nightly'
        run: |
          (echo 'SUBJECT=Nvim GTK development (prerelease) build';
           echo 'PRERELEASE=--prerelease') >> $GITHUB_ENV
          gh release delete nightly --yes || true
          git push origin :nightly || true
      - name: Publish release
        env:
          NVIM_GTK_VERSION: ${{ needs.linux.outputs.version }}
          NVIM_GTK_COMMIT: ${{ github.sha }}
          DEBUG: api
        run: |
          gh release create $TAG_NAME $PRERELEASE --title "$SUBJECT" --target $GITHUB_SHA nvim-gtk-linux-x86_64*
